// Code generated by packages/invoice-config/scripts/generate-cli-tokens.mjs; DO NOT EDIT.
package cmd

var tokenNetworkMap = map[string][]string{
	"BTC": {"Bitcoin"},
	"ETH": {"Ethereum"},
	"PAXG": {"Ethereum"},
	"SOL": {"Solana"},
	"USDC": {"Ethereum", "Solana"},
	"USDT": {"Ethereum", "Solana", "Tron"},
	"XAUT": {"Ethereum"},
	"ZEC": {"Zcash"},
}

var canonicalNetworkByAlias = map[string]string{
	"bitcoin": "Bitcoin",
	"btc": "Bitcoin",
	"eth": "Ethereum",
	"ethereum": "Ethereum",
	"sol": "Solana",
	"solana": "Solana",
	"tron": "Tron",
	"trx": "Tron",
	"zcash": "Zcash",
	"zec": "Zcash",
}
