import type { Metadata } from 'next';
import { ContentPage } from '@/_components/content-page';

export const metadata: Metadata = {
  title: 'Privacy Policy | WeaveCash',
  description:
    'WeaveCash Privacy Policy — how we handle your data with Privacy by Design, non-custodial infrastructure, and minimal data collection.',
};

export default function PrivacyPage() {
  return (
    <ContentPage title="Privacy Policy" subtitle="Effective Date: February 9, 2026">
      <p>
        At <strong className="text-slate-900 dark:text-white">WeaveCash</strong>, we believe
        financial sovereignty is a fundamental right. Our platform is built on the principle of{' '}
        <strong className="text-slate-900 dark:text-white">Privacy by Design</strong>, meaning we
        prioritize non-custodial infrastructure that minimizes the need for personal data
        collection. This policy explains how we handle the information you provide when using our
        &ldquo;No-Sign-Up&rdquo; invoicing and swap services.
      </p>

      {/* Section 1 */}
      <section>
        <h2 className="mb-6 text-2xl font-semibold text-slate-900 dark:text-white">
          1. Information We Collect
        </h2>
        <p className="mb-6">
          We collect information to facilitate your payments and provide a professional invoicing
          experience. This collection is divided into data you provide and data generated by the
          blockchain.
        </p>

        <h3 className="mb-4 text-xl font-medium text-slate-900 dark:text-white">
          A. Information You Provide (Optional)
        </h3>
        <p className="mb-4">
          To make our service useful even on the free tier, we allow you to provide the following
          optional data points. If provided, this data is stored on our secure servers to help you
          manage your business:
        </p>
        <ul className="mb-8 list-disc space-y-3 pl-6">
          <li>
            <strong className="text-slate-900 dark:text-white">Email Address:</strong> Used for
            sending payment notifications, receipts to your clients, and critical platform updates.
          </li>
          <li>
            <strong className="text-slate-900 dark:text-white">Business Name:</strong> Displayed
            on your invoices to provide a professional appearance for your brand.
          </li>
          <li>
            <strong className="text-slate-900 dark:text-white">Invoice Description:</strong> Used
            to detail the goods or services provided, helping both you and your buyer identify the
            purpose of the transaction.
          </li>
        </ul>

        <h3 className="mb-4 text-xl font-medium text-slate-900 dark:text-white">
          B. Wallet and Blockchain Data (Required)
        </h3>
        <p className="mb-4">
          Because WeaveCash operates on decentralized protocols, certain data is required for the
          system to function:
        </p>
        <ul className="mb-8 list-disc space-y-3 pl-6">
          <li>
            <strong className="text-slate-900 dark:text-white">Public Wallet Addresses:</strong>{' '}
            Your destination address (where you receive funds) and the buyer&rsquo;s sending
            address.
          </li>
          <li>
            <strong className="text-slate-900 dark:text-white">Transaction Metadata:</strong>{' '}
            Amount, asset type (e.g., BTC, USDC), and timestamps.
          </li>
          <li>
            <strong className="text-slate-900 dark:text-white">On-Chain Signatures:</strong> Data
            generated via <strong className="text-slate-900 dark:text-white">NEAR Chain Signatures</strong> to
            facilitate cross-chain settlement.
          </li>
        </ul>

        <h3 className="mb-4 text-xl font-medium text-slate-900 dark:text-white">
          C. Technical Data
        </h3>
        <ul className="list-disc space-y-3 pl-6">
          <li>
            <strong className="text-slate-900 dark:text-white">
              IP Addresses and Device Info:
            </strong>{' '}
            Collected temporarily for security purposes, such as preventing DDoS attacks and
            fraudulent activity.
          </li>
        </ul>
      </section>

      {/* Section 2 */}
      <section>
        <h2 className="mb-6 text-2xl font-semibold text-slate-900 dark:text-white">
          2. How We Use Your Data
        </h2>
        <p className="mb-4">
          We use your information strictly to provide and improve the WeaveCash experience:
        </p>
        <ul className="list-disc space-y-3 pl-6">
          <li>
            <strong className="text-slate-900 dark:text-white">Facilitating Swaps:</strong> Using{' '}
            <strong className="text-slate-900 dark:text-white">NEAR Intents</strong> to ensure
            your client&rsquo;s payment is converted and settled into your wallet.
          </li>
          <li>
            <strong className="text-slate-900 dark:text-white">Communication:</strong> Sending
            invoice links and payment confirmations via the optional email address provided.
          </li>
          <li>
            <strong className="text-slate-900 dark:text-white">Service Evolution:</strong> We
            track volume thresholds (tied to your public wallet address) to identify when you might
            benefit from our &ldquo;Pro&rdquo; subscription features.
          </li>
          <li>
            <strong className="text-slate-900 dark:text-white">Accounting:</strong> Saving your
            business name and invoice descriptions so you have a historical record of your
            &ldquo;Shadow Account&rdquo; transactions.
          </li>
        </ul>
      </section>

      {/* Section 3 */}
      <section>
        <h2 className="mb-6 text-2xl font-semibold text-slate-900 dark:text-white">
          3. Data Sovereignty and Custody
        </h2>
        <p className="mb-4 text-lg font-medium text-slate-900 dark:text-white">
          WeaveCash is a non-custodial platform.
        </p>
        <ul className="list-disc space-y-3 pl-6">
          <li>
            <strong className="text-slate-900 dark:text-white">No Access to Funds:</strong> We
            never have access to your private keys or your funds.
          </li>
          <li>
            <strong className="text-slate-900 dark:text-white">
              Open Source Verification:
            </strong>{' '}
            Our swap and settlement logic is open-source, allowing you to verify that we cannot
            divert or &ldquo;take&rdquo; buyer funds.
          </li>
          <li>
            <strong className="text-slate-900 dark:text-white">Public Ledger:</strong> Information
            written to the blockchain (addresses, amounts) is public and permanent. WeaveCash
            cannot delete or modify data once it is on-chain.
          </li>
        </ul>
      </section>

      {/* Section 4 */}
      <section>
        <h2 className="mb-6 text-2xl font-semibold text-slate-900 dark:text-white">
          4. Sharing and Disclosure
        </h2>
        <p className="mb-4">
          We do not sell, rent, or trade your personal data. We only share information with third
          parties when necessary to fulfill your transaction:
        </p>
        <ul className="list-disc space-y-3 pl-6">
          <li>
            <strong className="text-slate-900 dark:text-white">Intent Solvers:</strong> Your
            transaction details are shared with decentralized solvers to complete cross-chain
            swaps.
          </li>
          <li>
            <strong className="text-slate-900 dark:text-white">Service Providers:</strong> We may
            use highly vetted third parties for email delivery or cloud hosting, bound by strict
            confidentiality agreements.
          </li>
          <li>
            <strong className="text-slate-900 dark:text-white">Legal Requirements:</strong> We
            will only disclose your information if required by a valid legal order. Given our
            non-custodial nature, we typically do not possess custodial records of your
            transactions.
          </li>
        </ul>
      </section>

      {/* Section 5 */}
      <section>
        <h2 className="mb-6 text-2xl font-semibold text-slate-900 dark:text-white">
          5. Your Rights and Choices
        </h2>
        <ul className="list-disc space-y-3 pl-6">
          <li>
            <strong className="text-slate-900 dark:text-white">Opt-Out:</strong> You are never
            required to provide an email, business name, or invoice description to use our core
            services.
          </li>
          <li>
            <strong className="text-slate-900 dark:text-white">Access and Deletion:</strong> You
            may request to view or delete the optional data (email, business name) associated with
            your wallet address from our servers at any time.
          </li>
          <li>
            <strong className="text-slate-900 dark:text-white">Sovereign Control:</strong> Because
            your identity is tied to your wallet, you can stop using WeaveCash at any time without
            &ldquo;closing&rdquo; an account, as you own your financial rails.
          </li>
        </ul>
      </section>

      {/* Section 6 */}
      <section>
        <h2 className="mb-6 text-2xl font-semibold text-slate-900 dark:text-white">
          6. Updates to This Policy
        </h2>
        <p>
          As WeaveCash evolves (such as adding advanced subscription features), we will update this
          policy. We will notify users via the platform or through the optional email addresses
          provided.
        </p>
      </section>

      {/* Contact */}
      <section>
        <h2 className="mb-4 text-2xl font-semibold text-slate-900 dark:text-white">Contact Us</h2>
        <p>
          If you have questions about your privacy or our non-custodial architecture, please
          contact our team at{' '}
          <a
            href="mailto:support@weavecash.com"
            className="font-medium text-blue-600 hover:text-blue-700 dark:text-blue-500 dark:hover:text-blue-400"
          >
            support@weavecash.com
          </a>
          .
        </p>
      </section>
    </ContentPage>
  );
}
